# Generated by Django 4.0.2 on 2022-05-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('adress', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=18, null=True)),
                ('paiement', models.CharField(choices=[('Cash', 'Cash'), ('Orange Money', 'Orange Money'), ('Wave', 'Wave')], max_length=220)),
                ('choice', models.CharField(choices=[('Null', 'Null'), ('Complet', 'Complet'), ('Sec', 'Sec')], max_length=220, null=True)),
                ('date_rv', models.DateTimeField()),
                ('bank', models.CharField(max_length=220)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
