# Generated by Django 4.0.2 on 2022-05-15 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pressing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='bank',
        ),
    ]
