# Generated by Django 4.0.4 on 2022-05-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressing', '0002_remove_subscribe_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
