# Generated by Django 4.0.4 on 2022-05-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressing', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='choice',
            field=models.CharField(choices=[('Complet', 'Complet'), ('Sec', 'Nettoyage à sec')], max_length=220, null=True),
        ),
    ]
